In [41]:
import pandas as pd

In [42]:
df = pd.read_csv("../../gp_outputs/tests.csv")
df.head(3)

,Eval Time,Expression,F1 Score,Complexity
0,0.028526,column_MDVP:Shimmer,0.788018,0.2
1,0.024185,column_Shimmer:DDA,0.800268,0.2
2,0.021526,(column_MDVP:Fhi(Hz) + (((column_Shimmer:APQ3 - column_MDVP:RAP) - column_Shimmer:APQ3) + ((column_MDVP:RAP + column_Shimmer:DDA) - column_spread1))),0.788018,4.4

In [43]:
df_sorted = df.sort_values(by='F1 Score', ascending=False)
df_sorted.head(50)

,Eval Time,Expression,F1 Score,Complexity
142,0.017959,(column_MDVP:Jitter(%) - column_MDVP:RAP),0.816197,1.5
89,0.017959,(column_MDVP:Jitter(%) - column_MDVP:RAP),0.816197,1.5
121,0.017959,(column_MDVP:Jitter(%) - column_MDVP:RAP),0.816197,1.5
119,0.017959,(column_MDVP:Jitter(%) - column_MDVP:RAP),0.816197,1.5
23,0.018139,column_MDVP:APQ,0.800268,0.2
561,0.018243,(column_MDVP:Shimmer - (column_spread2 - (column_MDVP:Jitter(Abs) - (column_MDVP:APQ - column_spread2)))),0.800268,3.6
490,0.018725,column_MDVP:APQ,0.800268,0.2
562,0.018156,column_Shimmer:APQ3,0.800268,0.2
557,0.018121,column_MDVP:Jitter(Abs),0.800268,0.7
487,0.019291,column_Shimmer:APQ5,0.800268,0.2
508,0.017824,column_MDVP:APQ,0.800268,0.2
34,0.018272,column_MDVP:Jitter(Abs),0.800268,0.7
36,0.019630,(column_MDVP:APQ + (column_spread1 - ((column_spread1 + column_MDVP:APQ) + (column_MDVP:PPQ - column_Shimmer:APQ5)))),0.800268,4.1
43,0.018627,column_Shimmer:DDA,0.800268,0.2
553,0.019118,column_MDVP:RAP,0.800268,0.2
545,0.018324,column_Shimmer:APQ3,0.800268,0.2
535,0.018324,column_Shimmer:APQ3,0.800268,0.2
536,0.018229,column_Shimmer:APQ3,0.800268,0.2
491,0.018324,column_Shimmer:APQ3,0.800268,0.2
489,0.018217,column_Shimmer:APQ3,0.800268,0.2
452,0.019413,column_Shimmer:APQ5,0.800268,0.2
76,0.018825,column_MDVP:RAP,0.800268,0.2
427,0.020178,column_MDVP:RAP,0.800268,0.2
413,0.018773,(column_NHR + column_Shimmer:APQ3),0.800268,1.2
430,0.019466,((((column_D2 - column_spread1) - (column_MDVP:APQ + column_spread1)) - column_MDVP:Shimmer) + column_MDVP:Shimmer),0.800268,4.1
442,0.019167,column_Jitter:DDP,0.800268,0.2
63,0.018650,column_MDVP:RAP,0.800268,0.2
473,0.018475,column_Shimmer:APQ5,0.800268,0.2
482,0.018151,(column_MDVP:PPQ + (((column_D2 - column_MDVP:Jitter(%)) - (column_spread1 - column_Shimmer:APQ5)) + (column_Jitter:DDP + column_Jitter:DDP))),0.800268,5.3
460,0.019749,column_Shimmer:APQ5,0.800268,0.2
44,0.018293,column_MDVP:Jitter(Abs),0.800268,0.7
531,0.017998,(column_Shimmer:DDA + (column_MDVP:Jitter(%) - column_D2)),0.800268,2.7
576,0.018148,column_Jitter:DDP,0.800268,0.2
566,0.019508,column_Jitter:DDP,0.800268,0.2
1,0.024185,column_Shimmer:DDA,0.800268,0.2
233,0.018185,column_Shimmer:APQ3,0.800268,0.2
234,0.018764,column_Shimmer:DDA,0.800268,0.2
228,0.018454,column_Shimmer:APQ3,0.800268,0.2
160,0.019292,((column_Shimmer:DDA + (column_MDVP:Flo(Hz) - (column_MDVP:Jitter(Abs) + column_Shimmer:APQ3))) + (column_Shimmer:APQ3 - ((column_MDVP:APQ + column_MDVP:Jitter(Abs)) + column_MDVP:Flo(Hz)))),0.800268,5.0
152,0.018477,column_MDVP:APQ,0.800268,0.2
210,0.017880,column_Shimmer:APQ5,0.800268,0.2
8,0.018028,column_Shimmer:APQ5,0.800268,0.2
591,0.017981,column_MDVP:RAP,0.800268,0.2
586,0.018822,column_Jitter:DDP,0.800268,0.2
580,0.018449,column_Shimmer:APQ5,0.800268,0.2
192,0.018616,column_Shimmer:APQ5,0.800268,0.2
182,0.018793,column_Shimmer:APQ3,0.800268,0.2
171,0.018998,column_Jitter:DDP,0.800268,0.2
463,0.018677,(column_Shimmer:APQ3 - column_Shimmer:DDA),0.800268,1.0
50,0.018028,column_Shimmer:APQ5,0.800268,0.2